baseURL = "/"
title = "Love 30"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"

[params]
fancyTitle = "Love 30" # title for frontpage, may include image
copyright = "Love Björk"
description = "Kom som din hobby! <br />Maskerad och fåniga lekar efterföljt av middag och fest <br />Lördag 13 maj Uppsala"
startbuttonText = "OSA 10 mars"
startbuttonLink = "#four"
body_is_markdown = true
#custom_css = "foo.css"
#images = ["path_to_social_image_for_link_previews.jpg"]

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/OSA/'
title = "OSA"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one]
enable = true
title = 'Tema'
body = '''
Vem är du när ingen ser? Eller när du är i ditt verkliga esse? Du kanske har gröna fingrar? Kanske spenderar mer tid på gymmet än i soffan? Kanske bakar du flera gånger i veckan? Eller spelar fotboll? Ta på en matchande outfit och kom som din hobby! Bästa utklädnad koras givetvis!
'''

[[params.one.icon]] 
icon = "fa-gamepad"
style = "1"
label = "Lorem"

[[params.one.icon]]
icon = "fa-bicycle"
style = "2"
label = "Ipsum"

[[params.one.icon]]
icon = "fa-television"
style = "3"
label = "Dolor"


[params.two]
enable = true

[[params.two.section]]
img = "img/hus.jpeg"
title = 'Var? Hur? När?'
body = '13 Maj 15.30 ses vi vid på Ekolnäs vid Ekolns strand. Vi börjar med lekar i grupper, om vädret tillåter är vi utomhus då miljön runt huset är väldigt fin. Sen blir det middag och slutligen fest!'

[[params.two.section]]
img = "img/Presents.png"
title = 'Presenter?'
body = 'Prylar har jag så det räcker och blir över, jag har inget behov för fler. Er närvaro och det projekt det är att ta sig hit och hitta boende är mer än nog. Skulle det ändå vara så att ni absolut inte vill komma tomhänta prata gärna med Klara (070 557 97 43).'

[[params.two.section]]
img = "img/bed.jpg"
title = 'Bonede?'
body = 'Tyvärr är det ont om boende i direkt anslutning till gården, det finns däremot gott om hotell i centrala Uppsala dit det går stadsbussar till hela natten.'


[params.three]
enable = true
title = 'Ta sig hit'
body = '''
Vi kommer vara på Ekolnäs, ett fint gammalt hus vid Ekolns strand. Hit kan man ta både buss och bil.
'''

[[params.three.feature]]
icon = "fa-map"
title = "Adress"
body = "<a href=https://goo.gl/maps/VNpbv6wQujU17eaq5>Lövängsvägen 49, 756 55 Uppsala</a>"
[[params.three.feature]]
icon = "fa-bus"
title = "Buss"
body = "<a href=https://www.google.com/maps/dir/Uppsala+Centralstation,+Uppsala/F%C3%B6reningen+F%C3%B6reningsg%C3%A5rden+Ekolnsn%C3%A4s,+L%C3%B6v%C3%A4ngsv%C3%A4gen+49,+756+55+Uppsala/@59.8222781,17.593892,13z/data=!3m1!4b1!4m14!4m13!1m5!1m1!1s0x465fcbf9a0d697b1:0x1901cc46b512aff6!2m2!1d17.6465417!2d59.8581984!1m5!1m1!1s0x465fcbfc4ecacb23:0x41e5c3afce1aee63!2m2!1d17.6193224!2d59.7892327!3e3>Ta buss 11 från Uppsala Centralstation</a> åt endra hållet till Gullvivevägen, gå sedan de sista 500 metrarna."

[[params.three.feature]]
icon = "fa-users"
title = "Samåk med någon"
body = "Hör av dig till oss så ser vi om vi inte kan hitta någon att samåka med för miljön."

[params.cta]
enable = false
title = "Arcue ut vel commodo"
body = "Aliquam ut ex ut augue consectetur interdum endrerit imperdiet amet eleifend fringilla."

[[params.cta.link]]
href = "#"
text = "Activate"
special = true

[[params.cta.link]]
href = "#"
text = "Mer information"
special = false


[params.four]
enable = true
title = 'OSA'
body = '''
Anmäl att du kommer (eller att du tyvärr inte kan delta) via mail till love30@bixt.se <b>senast den 10 mars</b>. I anmälan vill vi gärna veta vem/vilka som kommer, evetuella allergier samt ifall ni planerar att förtära alkohol eller ej så att vi kan anpassa mat och dryck. 
'''

[params.contact]
enable = false
title = "OSA"
body = "Leave us a message."
phone = "+46 70 022 86 06"
#address = "1234 Somewhere Road<br />Some Place, Some State 0000<br />Some Country"
email = "love30@bixt.se"
subject = "New Submission!"
formspree_form_id = "example_invalid"

[languages.en]
weight = 0
languageName = "English"

