baseURL = "/"
title = "Love 30"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"

[params]
fancyTitle = "Love 30" # title for frontpage, may include image
copyright = "Love Björk"
#description = 'Another fine responsive<br />site template freebie<br />crafted by <a href="http://html5up.net">HTML5 UP</a>.<br />Ported to <a href="//gohugo.io">Hugo</a> by Simon Bruder.'
description = "Kom som din hobby!<br />Maskerad och fåniga lekar efterföljt av middag och fest<br />Lördag 13 maj Uppsala"
startbuttonText = "OSA"
startbuttonLink = "#"
body_is_markdown = true
#custom_css = "foo.css"
#images = ["path_to_social_image_for_link_previews.jpg"]

#[[params.menu.main]]
#url = '/'
#title = "Home"

#[[params.menu.main]]
#url = '/posts/'
#title = "Posts"  

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one]
enable = true
title = 'Tema'
body = '''
Vem är du när ingen ser? Eller när du är i ditt verkliga esse? Tiden flyger fram när man har fler hobbies än man vill erkänna. 30 år, när hände det? Tur är väl då att en hobby är att fixa galej!  
'''

[[params.one.icon]]
icon = "fa-diamond"
style = "1"
label = "Lorem"

[[params.one.icon]]
icon = "fa-heart-o"
style = "2"
label = "Ipsum"

[[params.one.icon]]
icon = "fa-code"
style = "3"
label = "Dolor"

[params.two]
enable = false

[[params.two.section]]
img = "img/pic01.jpg"
title = 'Magna primis lobortis<br />sed ullamcorper'
body = 'Aliquam ut ex ut augue consectetur interdum. Donec hendrerit imperdiet. Mauris eleifend fringilla nullam aenean mi ligula.'

[[params.two.section]]
img = "img/pic02.jpg"
title = 'Tortor dolore feugiat<br />elementum magna'
body = 'Aliquam ut ex ut augue consectetur interdum. Donec hendrerit imperdiet. Mauris eleifend fringilla nullam aenean mi ligula.'

[[params.two.section]]
img = "img/pic03.jpg"
title = 'Magna primis lobortis<br />sed ullamcorper'
body = 'Aliquam ut ex ut augue consectetur interdum. Donec hendrerit imperdiet. Mauris eleifend fringilla nullam aenean mi ligula.'

[params.three]
enable = true
title = 'Ta sig hit'
body = '''
Vi kommer vara på Ekolnäs, ett fint gammalt hus vid Ekolns strand. Hit kan man ta både buss och bil.
'''

[[params.three.feature]]
icon = "fa-paper-plane-o"
title = "Adress"
body = "Lövängsvägen 49, 756 55 Uppsala"

[[params.three.feature]]
icon = "fa-laptop"
title = "Buss"
body = "Ta buss x från Uppsala Centralstation till y"

[[params.three.feature]]
icon = "fa-code"
title = "Samåk med något"
body = "Hör av dig till oss så ser vi om vi inte kan hitta någon att samåka med för miljön."


[params.cta]
enable = false
title = "Arcue ut vel commodo"
body = "Aliquam ut ex ut augue consectetur interdum endrerit imperdiet amet eleifend fringilla."

[[params.cta.link]]
href = "#"
text = "Activate"
special = true

[[params.cta.link]]
href = "#"
text = "Learn More"
special = false

[params.contact]
enable = false
title = "Contact"
body = "Leave us a message."
phone = "+46 70 022 86 06"
address = "1234 Somewhere Road<br />Some Place, Some State 0000<br />Some Country"
email = "love30@bixt.se"
subject = "New Submission!"
formspree_form_id = "example_invalid"

#[params.social]
#twitter = ""
#facebook = ""
#instagram = ""
#dribble = ""

# language specific options

[languages.en]
weight = 0
languageName = "English"

#[languages.de]
#weight = 10
#languageName = "Deutsch"
